services:
  streamlit:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ../:/app
    working_dir: /app
    ports:
      - "8501:8501"
    command: ["streamlit", "run", "main.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
    networks:
      - internal

networks:
  internal:
    driver: bridge